### ISSUE TITLE
Cache Issue

### ISSUE THREAD

**Issue by silverbp** [fabric8io/fluent-plugin-docker_metadata_filter#1]
```
      if container_id && container_id[0]
        container_id = container_id[0]
        metadata = @cache.getset(container_id[0]){DockerMetadataFilter.get_metadata(container_id)}
```
In the above code it is using only the first character for the cache key making it highly likely that you'll run into cache issues or pulling metadata for the wrong container id.

it should be

```
      if container_id && container_id[0]
        container_id = container_id[0]
        metadata = @cache.getset(container_id){DockerMetadataFilter.get_metadata(container_id)}
```

**Comment by jimmidyson** [comment]
That is using match data for the container id regex - this is saying the full match, not first character so this should be fine.

It's something not working properly for you?

**Comment by jimmidyson** [comment]
Oh no you're totally right! Thank you!

Fancy putting in a PR?

**Comment by silverbp** [comment]
done, are you no longer using this? wondering if you came up with any better solutions?

**Comment by jimmidyson** [comment]
I'm now using kubernetes & we've implemented logging a bit differently, but similar idea really. This plugin should still be fine though.
