### ISSUE TITLE
Docker metadata being assigned to incorrect log messages.

### ISSUE THREAD

**Issue by bpsizemore** [fabric8io/fluent-plugin-docker_metadata_filter#5]
I am having an issue where in a large kubernetes cluster the docker metadata is often getting assigned to an incorrect log message. After testing with the non-cache version of this plugin it appears to be working properly. I submitted a pull request for the other user who fixed the issue by removing cache. #4

**Comment by jimmidyson** [comment]
Already fixed in #2, but I hadn't released to rubygems.org. Sorry for the trouble! Release coming now.

**Comment by jimmidyson** [comment]
v0.1.2 tagged & pushed including cache fix & moved to string keys. Thanks for the report!

**Comment by bpsizemore** [comment]
Thank you for the prompt response and fix!
